resources:
  - name: r-health-analytics
    description: R_Health Healthcare Analytics Platform - Renown Health RFP Demo

    # App configuration
    # The app will serve both the FastAPI backend and React frontend
    # Frontend is built and served as static files, backend handles API calls

command:
  - "python"
  - "backend/app_main.py"

env:
  - name: WAREHOUSE_ID
    value: "4b28691c780d9875"
  - name: CATALOG_NAME
    value: "hls_amer_catalog"
  - name: ENVIRONMENT
    value: "production"
