# R_Health Healthcare Analytics Platform - Databricks Apps Configuration
# Serves FastAPI backend + React frontend for 5 healthcare analytics scenarios

command:
  - "uvicorn"
  - "backend.app_simple:app"
  - "--host"
  - "0.0.0.0"
  - "--port"
  - "8000"

env:
  - name: ENVIRONMENT
    value: "demo"
